package model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DetalleDevolucion generated by hbm2java
 */
public class DetalleDevolucion  implements java.io.Serializable {


     private int idDetalleDevolucion;
     private Devolucion devolucion;
     private BigDecimal cantidad;
     private Set<DetalleProducto> detalleProductos = new HashSet<DetalleProducto>(0);

    public DetalleDevolucion() {
    }

	
    public DetalleDevolucion(int idDetalleDevolucion, Devolucion devolucion, BigDecimal cantidad) {
        this.idDetalleDevolucion = idDetalleDevolucion;
        this.devolucion = devolucion;
        this.cantidad = cantidad;
    }
    public DetalleDevolucion(int idDetalleDevolucion, Devolucion devolucion, BigDecimal cantidad, Set<DetalleProducto> detalleProductos) {
       this.idDetalleDevolucion = idDetalleDevolucion;
       this.devolucion = devolucion;
       this.cantidad = cantidad;
       this.detalleProductos = detalleProductos;
    }
   
    public int getIdDetalleDevolucion() {
        return this.idDetalleDevolucion;
    }
    
    public void setIdDetalleDevolucion(int idDetalleDevolucion) {
        this.idDetalleDevolucion = idDetalleDevolucion;
    }
    public Devolucion getDevolucion() {
        return this.devolucion;
    }
    
    public void setDevolucion(Devolucion devolucion) {
        this.devolucion = devolucion;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public Set<DetalleProducto> getDetalleProductos() {
        return this.detalleProductos;
    }
    
    public void setDetalleProductos(Set<DetalleProducto> detalleProductos) {
        this.detalleProductos = detalleProductos;
    }




}


