package model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Devolucion generated by hbm2java
 */
public class Devolucion  implements java.io.Serializable {


     private int idDevolucion;
     private TipoDevolucion tipoDevolucion;
     private Requisicion requisicion;
     private OrdenDeCompra ordenDeCompra;
     private Proveedor proveedor;
     private Cliente cliente;
     private BigDecimal cantidad;
     private Set<DetalleDevolucion> detalleDevolucions = new HashSet<DetalleDevolucion>(0);
     private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);

    public Devolucion() {
    }

	
    public Devolucion(int idDevolucion, TipoDevolucion tipoDevolucion, BigDecimal cantidad) {
        this.idDevolucion = idDevolucion;
        this.tipoDevolucion = tipoDevolucion;
        this.cantidad = cantidad;
    }
    public Devolucion(int idDevolucion, TipoDevolucion tipoDevolucion, Requisicion requisicion, OrdenDeCompra ordenDeCompra, Proveedor proveedor, Cliente cliente, BigDecimal cantidad, Set<DetalleDevolucion> detalleDevolucions, Set<Transaccion> transaccions) {
       this.idDevolucion = idDevolucion;
       this.tipoDevolucion = tipoDevolucion;
       this.requisicion = requisicion;
       this.ordenDeCompra = ordenDeCompra;
       this.proveedor = proveedor;
       this.cliente = cliente;
       this.cantidad = cantidad;
       this.detalleDevolucions = detalleDevolucions;
       this.transaccions = transaccions;
    }
   
    public int getIdDevolucion() {
        return this.idDevolucion;
    }
    
    public void setIdDevolucion(int idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public TipoDevolucion getTipoDevolucion() {
        return this.tipoDevolucion;
    }
    
    public void setTipoDevolucion(TipoDevolucion tipoDevolucion) {
        this.tipoDevolucion = tipoDevolucion;
    }
    public Requisicion getRequisicion() {
        return this.requisicion;
    }
    
    public void setRequisicion(Requisicion requisicion) {
        this.requisicion = requisicion;
    }
    public OrdenDeCompra getOrdenDeCompra() {
        return this.ordenDeCompra;
    }
    
    public void setOrdenDeCompra(OrdenDeCompra ordenDeCompra) {
        this.ordenDeCompra = ordenDeCompra;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public Set<DetalleDevolucion> getDetalleDevolucions() {
        return this.detalleDevolucions;
    }
    
    public void setDetalleDevolucions(Set<DetalleDevolucion> detalleDevolucions) {
        this.detalleDevolucions = detalleDevolucions;
    }
    public Set<Transaccion> getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set<Transaccion> transaccions) {
        this.transaccions = transaccions;
    }




}


