package model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Recursos generated by hbm2java
 */
public class Recursos  implements java.io.Serializable {


     private BigDecimal idRecurso;
     private TipoUsuario tipoUsuario;
     private String url;

    public Recursos() {
    }

	
    public Recursos(BigDecimal idRecurso, String url) {
        this.idRecurso = idRecurso;
        this.url = url;
    }
    public Recursos(BigDecimal idRecurso, TipoUsuario tipoUsuario, String url) {
       this.idRecurso = idRecurso;
       this.tipoUsuario = tipoUsuario;
       this.url = url;
    }
   
    public BigDecimal getIdRecurso() {
        return this.idRecurso;
    }
    
    public void setIdRecurso(BigDecimal idRecurso) {
        this.idRecurso = idRecurso;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


