package model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoDevolucion generated by hbm2java
 */
public class TipoDevolucion  implements java.io.Serializable {


     private int idTipoDevolucion;
     private String nombre;
     private String descripcion;
     private Set<Devolucion> devolucions = new HashSet<Devolucion>(0);

    public TipoDevolucion() {
    }

	
    public TipoDevolucion(int idTipoDevolucion, String nombre) {
        this.idTipoDevolucion = idTipoDevolucion;
        this.nombre = nombre;
    }
    public TipoDevolucion(int idTipoDevolucion, String nombre, String descripcion, Set<Devolucion> devolucions) {
       this.idTipoDevolucion = idTipoDevolucion;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.devolucions = devolucions;
    }
   
    public int getIdTipoDevolucion() {
        return this.idTipoDevolucion;
    }
    
    public void setIdTipoDevolucion(int idTipoDevolucion) {
        this.idTipoDevolucion = idTipoDevolucion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Devolucion> getDevolucions() {
        return this.devolucions;
    }
    
    public void setDevolucions(Set<Devolucion> devolucions) {
        this.devolucions = devolucions;
    }




}


