package model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoCliente generated by hbm2java
 */
public class TipoCliente  implements java.io.Serializable {


     private int idTipoCliente;
     private String nombre;
     private String descripcion;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public TipoCliente() {
    }

	
    public TipoCliente(int idTipoCliente, String nombre) {
        this.idTipoCliente = idTipoCliente;
        this.nombre = nombre;
    }
    public TipoCliente(int idTipoCliente, String nombre, String descripcion, Set<Cliente> clientes) {
       this.idTipoCliente = idTipoCliente;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.clientes = clientes;
    }
   
    public int getIdTipoCliente() {
        return this.idTipoCliente;
    }
    
    public void setIdTipoCliente(int idTipoCliente) {
        this.idTipoCliente = idTipoCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


