package com.ues.model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleProducto generated by hbm2java
 */
public class DetalleProducto  implements java.io.Serializable {


     private int idDetalleProducto;
     private DetalleRequisicion detalleRequisicion;
     private Producto producto;
     private DetalleDeOrdenCompra detalleDeOrdenCompra;
     private DetalleDevolucion detalleDevolucion;
     private String nombre;
     private BigDecimal cantidad;

    public DetalleProducto() {
    }

	
    public DetalleProducto(int idDetalleProducto, Producto producto, String nombre, BigDecimal cantidad) {
        this.idDetalleProducto = idDetalleProducto;
        this.producto = producto;
        this.nombre = nombre;
        this.cantidad = cantidad;
    }
    public DetalleProducto(int idDetalleProducto, DetalleRequisicion detalleRequisicion, Producto producto, DetalleDeOrdenCompra detalleDeOrdenCompra, DetalleDevolucion detalleDevolucion, String nombre, BigDecimal cantidad) {
       this.idDetalleProducto = idDetalleProducto;
       this.detalleRequisicion = detalleRequisicion;
       this.producto = producto;
       this.detalleDeOrdenCompra = detalleDeOrdenCompra;
       this.detalleDevolucion = detalleDevolucion;
       this.nombre = nombre;
       this.cantidad = cantidad;
    }
   
    public int getIdDetalleProducto() {
        return this.idDetalleProducto;
    }
    
    public void setIdDetalleProducto(int idDetalleProducto) {
        this.idDetalleProducto = idDetalleProducto;
    }
    public DetalleRequisicion getDetalleRequisicion() {
        return this.detalleRequisicion;
    }
    
    public void setDetalleRequisicion(DetalleRequisicion detalleRequisicion) {
        this.detalleRequisicion = detalleRequisicion;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public DetalleDeOrdenCompra getDetalleDeOrdenCompra() {
        return this.detalleDeOrdenCompra;
    }
    
    public void setDetalleDeOrdenCompra(DetalleDeOrdenCompra detalleDeOrdenCompra) {
        this.detalleDeOrdenCompra = detalleDeOrdenCompra;
    }
    public DetalleDevolucion getDetalleDevolucion() {
        return this.detalleDevolucion;
    }
    
    public void setDetalleDevolucion(DetalleDevolucion detalleDevolucion) {
        this.detalleDevolucion = detalleDevolucion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


