package com.ues.model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DetalleRequisicion generated by hbm2java
 */
public class DetalleRequisicion  implements java.io.Serializable {


     private int idDeastalleRequisicion;
     private Requisicion requisicion;
     private BigDecimal cantidad;
     private Set<DetalleProducto> detalleProductos = new HashSet<DetalleProducto>(0);

    public DetalleRequisicion() {
    }

	
    public DetalleRequisicion(int idDeastalleRequisicion, Requisicion requisicion, BigDecimal cantidad) {
        this.idDeastalleRequisicion = idDeastalleRequisicion;
        this.requisicion = requisicion;
        this.cantidad = cantidad;
    }
    public DetalleRequisicion(int idDeastalleRequisicion, Requisicion requisicion, BigDecimal cantidad, Set<DetalleProducto> detalleProductos) {
       this.idDeastalleRequisicion = idDeastalleRequisicion;
       this.requisicion = requisicion;
       this.cantidad = cantidad;
       this.detalleProductos = detalleProductos;
    }
   
    public int getIdDeastalleRequisicion() {
        return this.idDeastalleRequisicion;
    }
    
    public void setIdDeastalleRequisicion(int idDeastalleRequisicion) {
        this.idDeastalleRequisicion = idDeastalleRequisicion;
    }
    public Requisicion getRequisicion() {
        return this.requisicion;
    }
    
    public void setRequisicion(Requisicion requisicion) {
        this.requisicion = requisicion;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public Set<DetalleProducto> getDetalleProductos() {
        return this.detalleProductos;
    }
    
    public void setDetalleProductos(Set<DetalleProducto> detalleProductos) {
        this.detalleProductos = detalleProductos;
    }




}


