package com.ues.model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Lote generated by hbm2java
 */
public class Lote  implements java.io.Serializable {


     private int idLote;
     private Producto producto;
     private Bodega bodega;
     private BigDecimal cantidad;
     private String descripcion;

    public Lote() {
    }

	
    public Lote(int idLote, Producto producto, Bodega bodega, BigDecimal cantidad) {
        this.idLote = idLote;
        this.producto = producto;
        this.bodega = bodega;
        this.cantidad = cantidad;
    }
    public Lote(int idLote, Producto producto, Bodega bodega, BigDecimal cantidad, String descripcion) {
       this.idLote = idLote;
       this.producto = producto;
       this.bodega = bodega;
       this.cantidad = cantidad;
       this.descripcion = descripcion;
    }
   
    public int getIdLote() {
        return this.idLote;
    }
    
    public void setIdLote(int idLote) {
        this.idLote = idLote;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Bodega getBodega() {
        return this.bodega;
    }
    
    public void setBodega(Bodega bodega) {
        this.bodega = bodega;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


