package com.ues.model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idPersona;
     private Usuario usuario;
     private String nombre;
     private String apellido;
     private char genero;
     private String dui;
     private String nit;
     private Date fechaNac;
     private String direccion;
     private String correo;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);
     private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Telefono> telefonos = new HashSet<Telefono>(0);

    public Persona() {
    }

	
    public Persona(int idPersona, String nombre, String apellido, char genero, String dui, String nit, Date fechaNac, String direccion) {
        this.idPersona = idPersona;
        this.nombre = nombre;
        this.apellido = apellido;
        this.genero = genero;
        this.dui = dui;
        this.nit = nit;
        this.fechaNac = fechaNac;
        this.direccion = direccion;
    }
    public Persona(int idPersona, Usuario usuario, String nombre, String apellido, char genero, String dui, String nit, Date fechaNac, String direccion, String correo, Set<Empleado> empleados, Set<Proveedor> proveedors, Set<Cliente> clientes, Set<Telefono> telefonos) {
       this.idPersona = idPersona;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.genero = genero;
       this.dui = dui;
       this.nit = nit;
       this.fechaNac = fechaNac;
       this.direccion = direccion;
       this.correo = correo;
       this.empleados = empleados;
       this.proveedors = proveedors;
       this.clientes = clientes;
       this.telefonos = telefonos;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public char getGenero() {
        return this.genero;
    }
    
    public void setGenero(char genero) {
        this.genero = genero;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }
    public Set<Proveedor> getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set<Proveedor> proveedors) {
        this.proveedors = proveedors;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }
    public Set<Telefono> getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set<Telefono> telefonos) {
        this.telefonos = telefonos;
    }




}


