package com.ues.model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idProducto;
     private TipoProducto tipoProducto;
     private Proveedor proveedor;
     private String nombre4;
     private BigDecimal costo;
     private String codigoProducto;
     private String descripcion;
     private BigDecimal existencias;
     private Set<DetalleProducto> detalleProductos = new HashSet<DetalleProducto>(0);
     private Set<DetallePedido> detallePedidos = new HashSet<DetallePedido>(0);
     private Set<Lote> lotes = new HashSet<Lote>(0);

    public Producto() {
    }

	
    public Producto(int idProducto, TipoProducto tipoProducto, Proveedor proveedor, String nombre4, BigDecimal costo, String codigoProducto, BigDecimal existencias) {
        this.idProducto = idProducto;
        this.tipoProducto = tipoProducto;
        this.proveedor = proveedor;
        this.nombre4 = nombre4;
        this.costo = costo;
        this.codigoProducto = codigoProducto;
        this.existencias = existencias;
    }
    public Producto(int idProducto, TipoProducto tipoProducto, Proveedor proveedor, String nombre4, BigDecimal costo, String codigoProducto, String descripcion, BigDecimal existencias, Set<DetalleProducto> detalleProductos, Set<DetallePedido> detallePedidos, Set<Lote> lotes) {
       this.idProducto = idProducto;
       this.tipoProducto = tipoProducto;
       this.proveedor = proveedor;
       this.nombre4 = nombre4;
       this.costo = costo;
       this.codigoProducto = codigoProducto;
       this.descripcion = descripcion;
       this.existencias = existencias;
       this.detalleProductos = detalleProductos;
       this.detallePedidos = detallePedidos;
       this.lotes = lotes;
    }
   
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public TipoProducto getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(TipoProducto tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre4() {
        return this.nombre4;
    }
    
    public void setNombre4(String nombre4) {
        this.nombre4 = nombre4;
    }
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getExistencias() {
        return this.existencias;
    }
    
    public void setExistencias(BigDecimal existencias) {
        this.existencias = existencias;
    }
    public Set<DetalleProducto> getDetalleProductos() {
        return this.detalleProductos;
    }
    
    public void setDetalleProductos(Set<DetalleProducto> detalleProductos) {
        this.detalleProductos = detalleProductos;
    }
    public Set<DetallePedido> getDetallePedidos() {
        return this.detallePedidos;
    }
    
    public void setDetallePedidos(Set<DetallePedido> detallePedidos) {
        this.detallePedidos = detallePedidos;
    }
    public Set<Lote> getLotes() {
        return this.lotes;
    }
    
    public void setLotes(Set<Lote> lotes) {
        this.lotes = lotes;
    }




}


