package com.ues.model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Requisicion generated by hbm2java
 */
public class Requisicion  implements java.io.Serializable {


     private int idRequisicion;
     private Empleado empleado;
     private Cliente cliente;
     private Date fechaReq;
     private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);
     private Set<Devolucion> devolucions = new HashSet<Devolucion>(0);
     private Set<DetalleRequisicion> detalleRequisicions = new HashSet<DetalleRequisicion>(0);

    public Requisicion() {
    }

	
    public Requisicion(int idRequisicion, Empleado empleado, Cliente cliente, Date fechaReq) {
        this.idRequisicion = idRequisicion;
        this.empleado = empleado;
        this.cliente = cliente;
        this.fechaReq = fechaReq;
    }
    public Requisicion(int idRequisicion, Empleado empleado, Cliente cliente, Date fechaReq, Set<Transaccion> transaccions, Set<Devolucion> devolucions, Set<DetalleRequisicion> detalleRequisicions) {
       this.idRequisicion = idRequisicion;
       this.empleado = empleado;
       this.cliente = cliente;
       this.fechaReq = fechaReq;
       this.transaccions = transaccions;
       this.devolucions = devolucions;
       this.detalleRequisicions = detalleRequisicions;
    }
   
    public int getIdRequisicion() {
        return this.idRequisicion;
    }
    
    public void setIdRequisicion(int idRequisicion) {
        this.idRequisicion = idRequisicion;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFechaReq() {
        return this.fechaReq;
    }
    
    public void setFechaReq(Date fechaReq) {
        this.fechaReq = fechaReq;
    }
    public Set<Transaccion> getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set<Transaccion> transaccions) {
        this.transaccions = transaccions;
    }
    public Set<Devolucion> getDevolucions() {
        return this.devolucions;
    }
    
    public void setDevolucions(Set<Devolucion> devolucions) {
        this.devolucions = devolucions;
    }
    public Set<DetalleRequisicion> getDetalleRequisicions() {
        return this.detalleRequisicions;
    }
    
    public void setDetalleRequisicions(Set<DetalleRequisicion> detalleRequisicions) {
        this.detalleRequisicions = detalleRequisicions;
    }




}


