package com.ues.model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private int idTipoUsuario;
     private String nombre;
     private String descripcion;
     private Set<Recursos> recursoses = new HashSet<Recursos>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public TipoUsuario() {
    }

	
    public TipoUsuario(int idTipoUsuario, String nombre) {
        this.idTipoUsuario = idTipoUsuario;
        this.nombre = nombre;
    }
    public TipoUsuario(int idTipoUsuario, String nombre, String descripcion, Set<Recursos> recursoses, Set<Usuario> usuarios) {
       this.idTipoUsuario = idTipoUsuario;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.recursoses = recursoses;
       this.usuarios = usuarios;
    }
   
    public int getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(int idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Recursos> getRecursoses() {
        return this.recursoses;
    }
    
    public void setRecursoses(Set<Recursos> recursoses) {
        this.recursoses = recursoses;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


