package com.ues.model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoTransaccion generated by hbm2java
 */
public class TipoTransaccion  implements java.io.Serializable {


     private int idTipoTransaccion;
     private String nombre;
     private String descripcion;
     private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);

    public TipoTransaccion() {
    }

	
    public TipoTransaccion(int idTipoTransaccion, String nombre) {
        this.idTipoTransaccion = idTipoTransaccion;
        this.nombre = nombre;
    }
    public TipoTransaccion(int idTipoTransaccion, String nombre, String descripcion, Set<Transaccion> transaccions) {
       this.idTipoTransaccion = idTipoTransaccion;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.transaccions = transaccions;
    }
   
    public int getIdTipoTransaccion() {
        return this.idTipoTransaccion;
    }
    
    public void setIdTipoTransaccion(int idTipoTransaccion) {
        this.idTipoTransaccion = idTipoTransaccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Transaccion> getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set<Transaccion> transaccions) {
        this.transaccions = transaccions;
    }




}


