package com.ues.model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoProducto generated by hbm2java
 */
public class TipoProducto  implements java.io.Serializable {


     private int idTipoProducto;
     private String nombre;
     private String descripcion;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public TipoProducto() {
    }

	
    public TipoProducto(int idTipoProducto, String nombre) {
        this.idTipoProducto = idTipoProducto;
        this.nombre = nombre;
    }
    public TipoProducto(int idTipoProducto, String nombre, String descripcion, Set<Producto> productos) {
       this.idTipoProducto = idTipoProducto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.productos = productos;
    }
   
    public int getIdTipoProducto() {
        return this.idTipoProducto;
    }
    
    public void setIdTipoProducto(int idTipoProducto) {
        this.idTipoProducto = idTipoProducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


