package com.ues.model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoProveedor generated by hbm2java
 */
public class TipoProveedor  implements java.io.Serializable {


     private int idTipoProveedor;
     private String nombre;
     private String descripcion;
     private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);

    public TipoProveedor() {
    }

	
    public TipoProveedor(int idTipoProveedor, String nombre) {
        this.idTipoProveedor = idTipoProveedor;
        this.nombre = nombre;
    }
    public TipoProveedor(int idTipoProveedor, String nombre, String descripcion, Set<Proveedor> proveedors) {
       this.idTipoProveedor = idTipoProveedor;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.proveedors = proveedors;
    }
   
    public int getIdTipoProveedor() {
        return this.idTipoProveedor;
    }
    
    public void setIdTipoProveedor(int idTipoProveedor) {
        this.idTipoProveedor = idTipoProveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Proveedor> getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set<Proveedor> proveedors) {
        this.proveedors = proveedors;
    }




}


