package com.ues.model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1



/**
 * Transaccion generated by hbm2java
 */
public class Transaccion  implements java.io.Serializable {


     private int idTransaccion;
     private TipoTransaccion tipoTransaccion;
     private Inventario inventario;
     private Devolucion devolucion;
     private Requisicion requisicion;
     private OrdenDeCompra ordenDeCompra;

    public Transaccion() {
    }

	
    public Transaccion(int idTransaccion, TipoTransaccion tipoTransaccion, Inventario inventario) {
        this.idTransaccion = idTransaccion;
        this.tipoTransaccion = tipoTransaccion;
        this.inventario = inventario;
    }
    public Transaccion(int idTransaccion, TipoTransaccion tipoTransaccion, Inventario inventario, Devolucion devolucion, Requisicion requisicion, OrdenDeCompra ordenDeCompra) {
       this.idTransaccion = idTransaccion;
       this.tipoTransaccion = tipoTransaccion;
       this.inventario = inventario;
       this.devolucion = devolucion;
       this.requisicion = requisicion;
       this.ordenDeCompra = ordenDeCompra;
    }
   
    public int getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(int idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public TipoTransaccion getTipoTransaccion() {
        return this.tipoTransaccion;
    }
    
    public void setTipoTransaccion(TipoTransaccion tipoTransaccion) {
        this.tipoTransaccion = tipoTransaccion;
    }
    public Inventario getInventario() {
        return this.inventario;
    }
    
    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }
    public Devolucion getDevolucion() {
        return this.devolucion;
    }
    
    public void setDevolucion(Devolucion devolucion) {
        this.devolucion = devolucion;
    }
    public Requisicion getRequisicion() {
        return this.requisicion;
    }
    
    public void setRequisicion(Requisicion requisicion) {
        this.requisicion = requisicion;
    }
    public OrdenDeCompra getOrdenDeCompra() {
        return this.ordenDeCompra;
    }
    
    public void setOrdenDeCompra(OrdenDeCompra ordenDeCompra) {
        this.ordenDeCompra = ordenDeCompra;
    }




}


