package com.ues.model;
// Generated 30-may-2015 11:21:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private TipoUsuario tipoUsuario;
     private String nombreUsuario;
     private String contrasena;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, TipoUsuario tipoUsuario, String nombreUsuario, String contrasena, Date fechaCreacion) {
        this.idUsuario = idUsuario;
        this.tipoUsuario = tipoUsuario;
        this.nombreUsuario = nombreUsuario;
        this.contrasena = contrasena;
        this.fechaCreacion = fechaCreacion;
    }
    public Usuario(int idUsuario, TipoUsuario tipoUsuario, String nombreUsuario, String contrasena, Date fechaCreacion, Date fechaModificacion, Set<Persona> personas) {
       this.idUsuario = idUsuario;
      this.tipoUsuario = tipoUsuario;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.personas = personas;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
     public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
   public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


